name: shaunrydercup
favicon: null
layout_spectrum: 0.11314999242313206
typography_spectrum: 0.7105035099666566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9065857699606568
  lightness: 0.23847815557383
  saturation: 0.7119583543390036
  rhythmicContrast: 0.4298064378090203
purpose: []
